name: CI Build

# Test the build on every push or PR for every branch, except:
#  1. renovate created branches
#  2. only markdown files were updated

on:
  push:
    branches-ignore:
      - 'renovate/*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches-ignore:
      - 'renovate/*'
    paths-ignore:
      - '**.md'

concurrency: ci-${{ github.ref }}

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "${{ toJson(github) }}"
          env | sort
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }} # only update the cache on the default branch https://github.com/gradle/gradle-build-action#optimizing-cache-effectiveness
          arguments: clean build