name: Dummy Manual release

# Kick off a release manually, only allowed on the main branch
# Optionally specify the scope & stage to use for the SemVer for the release

on:
  workflow_call:
    inputs:
      stage:
        description: 'Stage'
        required: true
        type: string
      scope:
        description: 'Scope'
        required: true
        type: string
    outputs:
      version_tag:
        description: 'SemVer Tag Name'
        value: ${{ jobs.tag-and-create-release.outputs.version_tag }}

concurrency: main_release

jobs:
  tag-and-create-release:
    if: github.ref == 'refs/heads/main' # only release from main
    runs-on: ubuntu-latest

    outputs:
      version_tag: ${{ steps.changelog-commit.outputs.version_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Commit and Push Change Log
        id: changelog-commit
        run: |
          echo "0.4.4" > version.txt
          echo "v0.4.4" >> version.txt
          echo "::set-output name=version_tag::$(cat version.txt | tail -1)"