name: Publish the Release

on:
  workflow_call:
    inputs:
      version_tag:
        description: 'SemVer Tag Name for the Release to publish'
        required: true
        type: string

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'refs/tags/${{ inputs.version_tag }}'
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            clean build 
            -Psemver.overrideVersion=${{ inputs.version_tag }}
            -PgitHubTokenProp=${{ github.token }} 
            publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          OSS_USER: '${{ secrets.OSS_USER }}'
          OSS_TOKEN: '${{ secrets.OSS_TOKEN }}'
          OSS_STAGING_PROFILE_ID: '${{ secrets.OSS_STAGING_PROFILE_ID }}'
          ORG_GRADLE_PROJECT_signingKeyId: '${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}'
          ORG_GRADLE_PROJECT_signingKey: '${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}'
          ORG_GRADLE_PROJECT_signingPassword: '${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}'