name: Release and Publish

# Kick off a release manually, only allowed on the main branch
# Optionally specify the scope & stage to use for the SemVer for the release

on:
  workflow_dispatch:
    if: github.ref == 'refs/heads/main'
    inputs:
      stage:
        description: 'Stage'
        required: true
        default: 'final'
        type: choice
        options:
          - 'rc'
          - 'final'
      scope:
        description: 'Scope'
        required: true
        default: 'patch'
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'

jobs:
  release-and-tag:
    uses: nefilim/test-build/.github/workflows/release.yaml@main
    with:
      scope: ${{ github.event.inputs.scope }}
      stage: ${{ github.event.inputs.stage }}

  publish:
    uses: nefilim/test-build/.github/workflows/publish.yaml@main
    needs: release-and-tag
    with:
      version_tag: ${{ needs.release-and-tag.outputs.version_tag }}