name: Manual release

# Kick off a release manually, only allowed on the main branch
# Optionally specify the scope & stage to use for the SemVer for the release

on:
  workflow_dispatch:
    if: github.ref == 'refs/heads/main'
    inputs:
      stage:
        description: 'Stage'
        required: true
        default: 'final'
        type: choice
        options:
          - 'rc'
          - 'final'
      scope:
        description: 'Scope'
        required: true
        default: 'patch'
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'

jobs:
  tag-and-create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Tag and Create GitHub Release
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            clean build 
            -Psemver.main.scope=${{ inputs.scope }} -Psemver.main.stage=${{ inputs.stage }}  
            -PgitHubTokenProp=${{ github.token }} 
            githubRelease
        env:
          TOKEN_GITHUB_ACTION: '${{ secrets.GITHUB_TOKEN }}'